# Pytorch语法

查看当前版本

In [3]:
import torch
 
print(torch.__version__) # pytorch版本
print(torch.version.cuda) # cuda版本
print(torch.cuda.is_available()) # 查看cuda是否可用

#使用GPU or CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

2.5.1
12.1
True
cuda


创建张量

In [8]:
x=torch.arange(12)
print(x)
print(x.shape)
print(x.dtype) #默认是int64

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
torch.int64


In [9]:
X=x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [15]:
torch.tensor([[1.0,2.0,3.0],[4.5,2.3,1.2],[7.8,9.1,6.4]], dtype=torch.float32) #默认是float32

tensor([[1.0000, 2.0000, 3.0000],
        [4.5000, 2.3000, 1.2000],
        [7.8000, 9.1000, 6.4000]])

In [10]:
print(torch.rand(size=(3,4))) #随机生成一个3行4列的矩阵，元素在0-1之间
print(torch.zeros(size=(3,4))) #生成一个3行4列的全0矩阵
print(torch.ones(size=(3,4))) #生成一个3行4列的全1矩阵
print(torch.eye(3)) #生成一个3行3列的单位矩阵

tensor([[0.2453, 0.2293, 0.6436, 0.1612],
        [0.8451, 0.4631, 0.7837, 0.9754],
        [0.4977, 0.2971, 0.4593, 0.8924]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


运算符

In [30]:
x= torch.tensor([[1,2,3],[10,11,12]]) #将一个tensor放在GPU上，前提是GPU可用，否则放在CPU上
y= torch.tensor([[4,5,6],[7,8,9]])

print("x+y:", x+y)                  #加法运算
print("x*y:", x*y)                  #乘法运算

print("堆叠:", torch.stack([x, y]))          #堆叠运算
print("连接(行):", torch.cat([x, y], dim=0))     #连接运算
print("连接(列):", torch.cat([x, y], dim=1))     #连接运算，dim=0表示在行上连接，dim=1表示在列上连接

print("指数:", torch.exp(x))         #指数运算

print("索引:", x[0,1])              #索引运算，获取第一行第二列的元素

print("求和:", x.sum())                #求和运算，返回所有元素的和
print("每列的和:", x.sum(dim=0))           #求和运算，返回每列的和
print("每行的和:", x.sum(dim=1))           #求和运算，返回每行的和

x+y: tensor([[ 5,  7,  9],
        [17, 19, 21]])
x*y: tensor([[  4,  10,  18],
        [ 70,  88, 108]])
堆叠: tensor([[[ 1,  2,  3],
         [10, 11, 12]],

        [[ 4,  5,  6],
         [ 7,  8,  9]]])
连接(行): tensor([[ 1,  2,  3],
        [10, 11, 12],
        [ 4,  5,  6],
        [ 7,  8,  9]])
连接(列): tensor([[ 1,  2,  3,  4,  5,  6],
        [10, 11, 12,  7,  8,  9]])
指数: tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 5.9874e+04, 1.6275e+05]])
索引: tensor(2)
求和: tensor(39)
每列的和: tensor([11, 13, 15])
每行的和: tensor([ 6, 33])


广播：扩展张量以进行不同形状运算

In [33]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.tensor([(1,2,3)]) 
print("x+y:", x+y)     #广播机制，y会自动扩展成和x一样的形状，然后进行加法运算
print("x*y:", x*y)

x+y: tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])
x*y: tensor([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]])


内存:原地更新参数以节省内存和保持参数稳定

In [39]:
z=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(id(z))
z = z + 1
print(id(z)) # z的内存地址发生了变化，说明z是一个新的

1529827679808
1529827679248


In [40]:
z=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(id(z))
z[:] = z + 1
print(id(z)) # z的内存地址没有发生变化，说明z的内容被修改了，但z本身还是同一个对象

1529827677008
1529827677008


转换对象

In [43]:
a = x.numpy() # 将一个tensor转换成numpy数组
print(a)
b = torch.tensor(a) # 将一个numpy数组转换成tensor
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
